mailganer/mailganer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('sender.urls')),
    url('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        url(
            "__debug__/",
            include(debug_toolbar.urls),
        ),
    )

mailganer/sender/urls.py
from django.conf.urls import url

from sender import views

app_name = 'sender'

urlpatterns = [
    url(r'^newsletter/track$', views.NewsletterTrackView.as_view(), name='read'),
    url(r'^newsletter/(?P<newsletter_id>[0-9]+)/$', views.NewsletterDetailView.as_view(), name='newsletter'),
    url(r'^$', views.MainView.as_view(), name='main'),
]

mailganer/sender/models.py
# -*- coding: utf-8 -*-

from django.db import models

from tinymce import models as tinymce_models


class Subscriber(models.Model):
    email = models.EmailField(
        'электронная почта',
        unique=True,
    )
    first_name = models.CharField(
        'имя',
        max_length=100,
    )
    last_name = models.CharField(
        'фамилия',
        max_length=100,
    )
    birthday = models.DateField(
        'день рождения',
    )

    class Meta:
        verbose_name = 'подписчик'
        verbose_name_plural = 'подписчики'

    def __str__(self):
        return self.email if len(self.email) <= 21 else self.email[:18] + '...'



class Newsletter(models.Model):
    created_at = models.DateTimeField(
        'дата создания',
        auto_now_add=True,
        null=True,
    )
    subject = models.CharField(
        'тема',
        max_length=100,
    )
    message = tinymce_models.HTMLField(
        'сообщение',
    )
    reached_subs = models.IntegerField(
        verbose_name='количество получивших рассылку',
        default=0,
    )
    read_subs = models.ManyToManyField(
        Subscriber,
        verbose_name='прочитавшие подписчики',
    )

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'

    def __str__(self):
        return self.subject if len(self.subject) <= 21 else self.subject[:18] + '...'

mailganer/sender/forms.py
# -*- coding: utf-8 -*-

from django import forms
from sender import models
from tinymce.widgets import TinyMCE


class BaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseModelForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'
            if field.errors:
                field.field.widget.attrs['class'] += ' is-invalid'

    class Meta:
        abstract = True


class NewsletterForm(BaseModelForm):

    class Meta:
        model = models.Newsletter

        exclude = (
            'created_at',
            'reached_subs',
            'read_subs',
        )
        labels = {
            'subject': 'Тема письма',
            'message': 'Сообщение',
        }
        help_texts = {
            'message': 'Для персонализации сообщения выберете переменную нажав на значок тега в панели инструментов',
        }
        widgets = {'message': TinyMCE()}
        error_messages = {
            'subject': {
                'required': 'Пожалуйста, заполните тему письма',
            },
            'message': {
                'required': 'Пожалуйста, заполните Ваше сообщение',
            },
        }

mailganer/sender/views.py
# -*- coding: utf-8 -*-

from django.core.mail import send_mail
import django.db
from sender.forms import NewsletterForm
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template import Template, Context
import django.views.generic

from sender.models import Subscriber, Newsletter

from PIL import Image

TEMPLATE_HEAD = '<html><body>'
TEMPLATE_TAIL = '<img src="http://localhost:8000/newsletter/track?newsletter_id={{newsletter_id}}&subscriber_id={{subscriber_id}}" width="1" height="1" /></body></html>'


class MainView(
    django.views.generic.base.TemplateResponseMixin,
    django.views.generic.View,
):
    template_name = 'sender/main.html'

    def get(self, request, *args, **kwargs):
        all_newsletters = Newsletter.objects.values('id', 'subject', 'created_at').order_by('-created_at')
        form = NewsletterForm()
        return self.render_to_response(
            {"newsletters": all_newsletters, "form": form}
        )

    def post(self, request, *args, **kwargs):
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            form = NewsletterForm(request.POST)

            if form.is_valid():
                subscribers = Subscriber.objects.values("first_name", "last_name", "birthday", "email", "id")

                with django.db.transaction.atomic():
                    new_letter = form.save(commit=False)
                    new_letter.reached_subs = subscribers.count()
                    new_letter.save()

                message = TEMPLATE_HEAD + new_letter.message + TEMPLATE_TAIL
                template = Template(message)

                for subscriber in subscribers:
                    html_message = template.render(
                        Context({
                            'first_name': subscriber['first_name'],
                            'last_name': subscriber['last_name'],
                            'birthday': subscriber['birthday'],
                            'email': subscriber['email'],
                            'newsletter_id': new_letter.id,
                            'subscriber_id': subscriber['id'],
                        })
                    )

                    send_mail(
                        new_letter.subject,
                        html_message,
                        'from@example.com',
                        [subscriber['email']],
                        html_message=html_message,
                    )

                return JsonResponse({
                    "success": True,
                    "message": "Рассылка успешно отправлена!",
                    "newsletter": {
                        "id": new_letter.id,
                        "subject": new_letter.subject,
                        "created_at": new_letter.created_at.strftime('%d.%m.%Y %H:%M'),
                    }
                })

            return JsonResponse({"success": False, "errors": form.errors}, status=400)

        return JsonResponse({"success": False, "message": "Некорректный запрос"}, status=400)


class NewsletterDetailView(django.views.generic.detail.DetailView):
    model = Newsletter
    template_name = "sender/detail.html"
    pk_url_kwarg = 'newsletter_id'

    def get_object(self, queryset=None):
        return super(NewsletterDetailView, self).get_object(queryset)

    def get_context_data(self, **kwargs):
        context = super(NewsletterDetailView, self).get_context_data(**kwargs)
        newsletter = self.object

        viewed_subscribers = newsletter.read_subs.values('email')

        context['viewed_subscribers'] = viewed_subscribers
        context['viewed_subscribers_count'] = viewed_subscribers.count()
        context['reached_subs_count'] = newsletter.reached_subs

        return context


class NewsletterTrackView(
    django.views.generic.View,
):
    def get(self, request, *args, **kwargs):
        newsletter_id = request.GET.get('newsletter_id')
        subscriber_id = request.GET.get('subscriber_id')

        current_newsletter = get_object_or_404(Newsletter, id=newsletter_id)
        current_subscriber = get_object_or_404(Subscriber, id=subscriber_id)

        with django.db.transaction.atomic():
            if current_subscriber not in current_newsletter.read_subs.all():
                current_newsletter.read_subs.add(current_subscriber)
                current_newsletter.save()

        image = Image.new("RGB", (1, 1), color=(255, 255, 255))
        response = HttpResponse(content_type="image/png")
        image.save(response, format="PNG")

        response["Cache-Control"] = "no-cache"
        response["Content-Disposition"] = "inline; filename=tracking_pixel.png"
        return response

mailganer/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Рассылки{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script src="https://cdn.tiny.cloud/1/yfum3fz2yjwynohrs67dtxy3h14qbdyzlsumbi0pnfoy7e4o/tinymce/7/plugins.min.js" referrerpolicy="origin"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <main class="flex-grow-1">
      {% block content %}Контент{% endblock %}
    </main>
  </body>
</html>

mailganer/templates/includes/card.html
<a href="{% url 'sender:newsletter' newsletter_id=newsletter.id %}" class="text-decoration-none">
  <div class="card my-3">
    <div class="card-body justify-content-between d-flex align-items-center">
      <p class="fs-3 mb-0">{{ newsletter.subject }}</p>
      <p class="fs-3 mb-1">{{ newsletter.created_at|date:"d.m.Y H:i" }}</p>
    </div>
  </div>
</a>

mailganer/templates/includes/form.html
{% for field in form %}
  <div class="mb-3">
    <label class="form-label" for="{{ field.id_for_label }}">
      {{ field.label }}
    </label>

    {{ field }}

    {% if field.errors %}
      {% for error in field.errors %}
        <div id="{{ field.id_for_label }}Help" class="invalid-feedback">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% elif field.help_text %}
      <div id="{{ field.id_for_label }}Help" class="form-text">
        {{ field.help_text }}
      </div>
    {% endif %}
  </div>
{% endfor %}

mailganer/templates/includes/habit_card.html
<div class="col-12">
  {% comment %} <a href="{% url 'habits:settings' pk=habit.id %}" class="text-decoration-none"> {% endcomment %}
    <div class="card" style="min-height: 80px; max-width: 934px;">
      <div class="card-body justify-content-between d-flex align-items-center">
        <p class="fs-3 mb-0">{{ newsletter.subject }}</p>
          <p class="fs-3 mb-1">{{ newsletter.created_at|date:"d.m.Y H:i" }}</p>
      </div>
    </div>
  {% comment %} </a> {% endcomment %}
</div>

mailganer/templates/sender/detail.html
{% extends "base.html" %}

{% block title %}Отправленная рассылка{% endblock %}

{% block content %}
  <div class="container-fluid" style="padding: 2rem;">
    <div class="container-fluid d-flex justify-content-left align-items-center">
      <a href="{% url 'sender:main' %}" class="btn btn-outline-primary" role="button" aria-disabled="true">Назад</a>
      <h1 class="mx-3">Отправленная рассылка</h1>
    </div>

    <div class="container g-3 mx-1 my-2" style="min-height: 80px; max-width: 934px;">
      <div class="card my-3">
        <div class="card-header">
          <b>{{ object.subject }}</b>
        </div>
        <div class="card-body">
          <p class="card-text">{{ object.message|safe }}</p>
        </div>
      </div>

      <div class="my-3">
        <p class="fs-4 mb-0 my-3"><b>Дата отправления:</b> {{ object.created_at }}</p>
      </div>

      <div class="my-3">
        {% if viewed_subscribers %}
          <p class="fs-4 mb-0 my-3">Подписчики, просмотревшие рассылку:</p>

          <ul class="list-group my-3">
            {% for subscriber in viewed_subscribers %}
              <li class="list-group-item">{{ subscriber.email }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        <p>Рассылку просмотрело {{ viewed_subscribers_count }} из {{ reached_subs_count }} подписчиков</p>
      </div>
    </div>
  </div>
  {% endblock %}

mailganer/templates/sender/main.html
{% extends "base.html" %}

{% block title %}Moи рассылки{% endblock %}

{% block content %}
  <div class="container-fluid" style="padding: 2rem;">
    <div class="container-fluid d-flex justify-content-between">
      <h1>Мои рассылки</h1>

      <!-- Кнопка-триггер модального окна создания рассылки -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createNewsletterModal">
        Создать
      </button>
    </div>

    <!-- Все рассылки -->
    <div class="container g-3 mx-1 my-2" style="max-width: 934px;">
      {% for newsletter in newsletters %}
        {% include "includes/card.html" with newsletter=newsletter %}
      {% empty %}
        <p class="fs-4">Жми кнопку <b>Создать</b> для новой рассылки</p>
      {% endfor %}
    </div>
  </div>

  <!-- Модальное окно создания рассылки -->
  <div class="modal modal-lg fade" id="createNewsletterModal" tabindex="-1" aria-labelledby="createNewsletterModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="createNewsletterModalLabel">Создать новую рассылку</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>

        <!-- Форма создания рассылки -->
        <form id="newsletter-form" method="post" action="{% url 'sender:main' %}" novalidate>
          <div class="modal-body">
            {% csrf_token %}
            {% include "includes/form.html" with form=form %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script>
    tinymce.init({
      selector: '#id_message',
      language: 'ru',
      plugins: [
        'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'image', 'link', 'lists', 'media', 'searchreplace', 'table', 'visualblocks', 'wordcount',
        'checklist', 'mediaembed', 'casechange', 'export', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'editimage', 'advtemplate', 'mentions', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown','importword', 'exportword', 'exportpdf'
      ],
      toolbar: 'mergetags | undo redo | blocks fontsize | bold italic underline strikethrough',
      mergetags_list: [
        { value: 'first_name', title: 'Имя' },
        { value: 'last_name', title: 'Фамилия' },
        { value: 'birthday', title: 'День рождения' },
        { value: 'email', title: 'Email' },
      ],
    });
  </script>

  <script>
    $(document).ready(function() {
      $('#newsletter-form').submit(function(event) {
        event.preventDefault();

        var form = $(this);
        var formData = form.serialize();

        $.ajax({
          type: form.attr('method'),
          url: form.attr('action'),
          data: formData,
          dataType: 'json',

          beforeSend: function() {
            form.find('button[type="submit"]').prop('disabled', true);
          },

          success: function(response) {
            $('#createNewsletterModal').modal('hide');
            form.trigger('reset');

            var newCard = `
              <a href="/newsletter/${response.newsletter.id}/" class="text-decoration-none">
                  <div class="card my-3">
                      <div class="card-body justify-content-between d-flex align-items-center">
                          <p class="fs-3 mb-0">${response.newsletter.subject}</p>
                          <p class="fs-3 mb-1">${response.newsletter.created_at}</p>
                      </div>
                  </div>
              </a>
            `;
            $(".container").prepend(newCard);

            var alertMessage = `
              <div class="alert alert-success alert-dismissible fade show my-3" role="alert">
                ${response.message}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
              </div>
            `;
            $(".container").prepend(alertMessage);
          },

          error: function(xhr) {
            form.find('.is-invalid').removeClass('is-invalid');
            form.find('.invalid-feedback').remove();

            if (xhr.responseJSON && xhr.responseJSON.errors) {
              $.each(xhr.responseJSON.errors, function(field, messages) {
                var inputField = $('#id_' + field);
                inputField.addClass('is-invalid');
                inputField.after(`<div class="invalid-feedback">${messages.join('<br>')}</div>`);
              });
            }
          },

          complete: function() {
            form.find('button[type="submit"]').prop('disabled', false);
          }
        });
      });
    });
  </script>
{% endblock %}

mailganer/templates/sender/newsletter.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid" style="padding: 1rem;">
    <div class="container-fluid d-flex justify-content-between">
      <h1>Мои рассылки</h1>

      <!-- Кнопка-триггер модального окна создания рассылки -->
      <button type="button" class="btn btn-primary hero-btn" data-bs-toggle="modal" data-bs-target="#createHabitModal">
        Создать
      </button>
    </div>

    <!-- Все рассылки -->
    <div class="row g-3 mx-1 my-2">
      {% for newsletter in newsletters %}
        {% include "includes/habit_card.html" with newsletter=newsletter %}
      {% empty %}
        <div class="col-12">
          <p class="fs-4">Жми кнопку <b class="prime-color">Создать</b> для новой рассылки</p>

        </div>
      {% endfor %}
    </div>
  </div>

  <!-- Модальное окно создания рассылки -->
  <div class="modal modal-lg fade" id="createHabitModal" tabindex="-1" aria-labelledby="createHabitModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="createHabitModalLabel">Создать новую рассылку</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>

        <!-- Форма создания рассылки -->
        <form method="post" novalidate>
          <div class="modal-body">
            {% csrf_token %}
            {% include "includes/form.html" with form=form %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary">Сохранить</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Если форма невалидна, открываем модальное окно при перезагрузке -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if form.errors %}
          var myModal = new bootstrap.Modal(document.getElementById('createHabitModal'));
          myModal.show();
        {% endif %}

        var createHabitModal = document.getElementById('createHabitModal');
        var form = createHabitModal.querySelector('form');

        function resetForm() {
          form.reset();
          var invalidFields = form.querySelectorAll('.is-invalid, .is-valid');
          invalidFields.forEach(function(field) {
            field.classList.remove('is-invalid', 'is-valid');
          });

          var errorMessages = form.querySelectorAll('.invalid-feedback, .valid-feedback');
          errorMessages.forEach(function(message) {
            message.textContent = '';
          });
        }

        createHabitModal.addEventListener('hidden.bs.modal', function() {
          resetForm();
        });

        var closeButton = createHabitModal.querySelector('[data-bs-dismiss="modal"]');
        closeButton.addEventListener('click', function() {
          resetForm();
        });
      });
    </script>

  {% endblock %}